---
title: "smFISH quantification report `r format(Sys.Date(), '%Y-%m-%d')`"
author: "Naly Torres"
date: "8/28/2024"
output: html_document
---


```{r echo=FALSE, warning=FALSE} 

library(png)
library(knitr)
library(ggplot2)
library(tidyr)
library(dplyr)

#install.packages("ggplot2")
library(ggsignif)
#install.packages("scales")
library(svglite)
library(ggridges)
library(scales)


```


Violin Plots

```{r}

# Parent directory containing CSV files for all conditions
parent_directory <- "/Users/nalytorres/Documents/01_ce-bigfish-post-analysis/02_data/ce_bigfish_total_abundance/N2_lin-41"


# Function to read CSV, replace Image ID with CSV name, and modify column names
read_modify_csv <- function(file_path, subdirectory) {
  my_df <- read.csv(file_path)
  my_df$Image_ID <- basename(file_path)
  my_df$subdirectory <- subdirectory
  my_df <- my_df[, colnames(my_df) != "X"]
  current_colnames <- colnames(my_df)
  new_colnames <- gsub("\\.", " ", current_colnames)
  colnames(my_df) <- new_colnames
  return(my_df)
}

# List all subdirectories (conditions) in the parent directory
subdirectories <- list.dirs(parent_directory, full.names = FALSE, recursive = FALSE)

# Initialize an empty list to store data frames
all_data <- list()

# Loop through subdirectories (conditions)
for (subdirectory in subdirectories) {
  # List all CSV files in the current subdirectory
  csv_files <- list.files(path = file.path(parent_directory, subdirectory), pattern = "*.csv", full.names = TRUE)
  
  # Loop through CSV files, read data, replace Image ID, and modify column names
  for (file_path in csv_files) {
    current_data <- read_modify_csv(file_path, subdirectory)
    all_data[[file_path]] <- current_data
  }
}

# Combine all data frames into one data frame
combined_data <- bind_rows(all_data)

# Create a new column 'rep' by extracting the last item after the last '_'
combined_data$rep <- sub(".*_(.*)$", "\\1", combined_data$subdirectory)

# Extract the first part of the subdirectory string (cell stage)
combined_data <- combined_data %>%
  mutate(cell_stage = sub("([0-9]+-cell).*", "\\1", subdirectory))

# View the updated data frame
str(combined_data)


# Rename columns for simplicity
combined_data <- combined_data %>%
  rename(
    `set_3_mRNA_molecules` = `set 3 mRNA molecules`,
    `lin_41_mRNA_molecules` = `lin 41 mRNA molecules`
  )

# Remove columns related to clusters
combined_data <- combined_data %>%
  select(
    `rep`,
    `cell_stage`,
    `set_3_mRNA_molecules`,
    `lin_41_mRNA_molecules`
  )

# Pivot the data to long format with renamed columns
long_data <- combined_data %>%
  pivot_longer(
    cols = starts_with("set_3_mRNA") | starts_with("lin_41_mRNA"),
    names_to = "mRNA_type",
    values_to = "abundance"
  ) %>%
  mutate(mRNA_type = recode(mRNA_type,
                            `set_3_mRNA_molecules` = "set-3_mRNA",
                            `lin_41_mRNA_molecules` = "lin-41_mRNA"),
         combined_category = paste(cell_stage, mRNA_type, sep = "_")
  )


# Assign the updated data frame to combined_data
combined_data <- long_data

print(combined_data)
str(combined_data)





```
```{r}
library(ggplot2)
library(dplyr)

# Define the custom order for combined_category
custom_order <- c("2-cell_set-3_mRNA", "4-cell_set-3_mRNA",
                  "2-cell_lin-41_mRNA", "4-cell_lin-41_mRNA")

# Convert combined_category to a factor to ensure correct ordering on the x-axis
plot_data <- combined_data %>%
  mutate(combined_category = factor(combined_category, levels = custom_order)) %>%
  group_by(mRNA_type) %>%
  filter(!is_outlier(abundance)) %>%
  ungroup()

# Function to identify outliers based on IQR
is_outlier <- function(x) {
  IQR_value <- IQR(x)
  Q1 <- quantile(x, 0.25)
  Q3 <- quantile(x, 0.75)
  lower_bound <- Q1 - 1.5 * IQR_value
  upper_bound <- Q3 + 1.5 * IQR_value
  x < lower_bound | x > upper_bound
}

# Specify color for each combined_category
fill_colors <- c("2-cell_set-3_mRNA" = "lightblue", 
                  "4-cell_set-3_mRNA" = "lightblue", 
                  "2-cell_lin-41_mRNA" = "lightcoral", 
                  "4-cell_lin-41_mRNA" = "lightcoral")

# Create the plot
my_plot <- ggplot(plot_data, aes(x = combined_category, y = abundance, fill = combined_category)) +
  geom_violin(alpha = 0.4, color = "white", size = 0.5, position = position_dodge(width = 0.75)) +
  geom_boxplot(width = 0.1, position = position_dodge(width = 0.75), outlier.shape = NA) +
  geom_jitter(aes(color = rep), height = 0, width = 0.2, size = 1) +
  labs(title = "Abundance of maternally inherited transcripts by cell stage",
       x = "Cell Stage",
       y = "Total mRNA Abundance",
       fill = "mRNA species",
       color = "Replicate") +  # Set the legend title for color
  scale_fill_manual(values = fill_colors,
                    breaks = names(fill_colors),
                    labels = c("set-3", "set-3", "lin-41", "lin-41")) +
  scale_color_manual(values = c("rep1" = "black", "rep2" = "red", "rep3" = "blue"), 
                     breaks = c("rep1", "rep2", "rep3"), 
                     labels = c("Rep 1", "Rep 2", "Rep 3")) +
  scale_x_discrete(labels = c("2-cell_set-3_mRNA" = "2-cell",
                              "4-cell_set-3_mRNA" = "4-cell",
                              "2-cell_lin-41_mRNA" = "2-cell",
                              "4-cell_lin-41_mRNA" = "4-cell")) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        plot.subtitle = element_text(size = 14),
        axis.title = element_text(size = 13, face = "bold"),
        axis.text = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        strip.background = element_rect(fill = "lightgray", color = "black"),
        strip.text = element_text(size = 14, face = "bold")) +  # Customize facet labels
  guides(fill = guide_legend(nrow = 2)) +  # Limit the legend to two rows
  facet_wrap(~ mRNA_type, scales = "fixed")  # Fixed y-axis across facets

# Display the plot
print(my_plot)






```



```{r}
library(ggplot2)
library(dplyr)

# Define the custom order for combined_category
custom_order <- c("2-cell_set-3_mRNA", "4-cell_set-3_mRNA",
                  "2-cell_lin-41_mRNA", "4-cell_lin-41_mRNA")

# Convert combined_category to a factor to ensure correct ordering on the x-axis
plot_data <- combined_data %>%
  mutate(combined_category = factor(combined_category, levels = custom_order))

# Specify color for each mRNA species (aggregate colors)
fill_colors <- c("set-3_mRNA" = "skyblue", 
                  "lin-41_mRNA" = "lightcoral")

# Create the plot
p <- ggplot(plot_data, aes(x = combined_category, y = abundance, fill = mRNA_type)) +
  geom_violin(alpha = 0.6, color = "white", size = 0.8, position = position_dodge(width = 0.75)) +
  geom_boxplot(width = 0.1, position = position_dodge(width = 0.75), outlier.shape = NA) +
  geom_jitter(aes(color = rep), height = 0, width = 0.2, size = 1) +
  labs(title = "Abundance of maternally inherited transcripts by cell stage",
       x = "mRNA species",
       y = "Abundance",
       fill = "mRNA species",
       color = "Replicate") +  # Set the legend title for color
  scale_fill_manual(values = fill_colors,
                    breaks = c("set-3_mRNA", "lin-41_mRNA"),
                    labels = c("set-3 mRNA", "lin-41 mRNA")) +
  scale_color_manual(values = c("rep1" = "black", "rep2" = "red", "rep3" = "blue"), 
                     breaks = c("rep1", "rep2", "rep3"), 
                     labels = c("Rep 1", "Rep 2", "Rep 3")) +
  scale_x_discrete(labels = c("2-cell_set-3_mRNA" = "2-cell set-3",
                              "2-cell_lin-41_mRNA" = "2-cell lin-41",
                              "4-cell_set-3_mRNA" = "4-cell set-3",
                              "4-cell_lin-41_mRNA" = "4-cell lin-41")) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        plot.subtitle = element_text(size = 14),
        axis.title = element_text(size = 13, face = "bold"),
        axis.text = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12)) +
  guides(fill = guide_legend(nrow = 2))  # Limit the legend to two rows

# Display the plot
print(p)


```






```{r}
library(ggplot2)
library(dplyr)

# Define the custom order for combined_category
custom_order <- c("2-cell_set-3_mRNA", "4-cell_set-3_mRNA",
                  "2-cell_lin-41_mRNA", "4-cell_lin-41_mRNA")

# Convert combined_category to a factor to ensure correct ordering on the x-axis
plot_data <- combined_data %>%
  mutate(combined_category = factor(combined_category, levels = custom_order))

# Specify color for each combined_category
fill_colors <- c("2-cell_set-3_mRNA" = "lightblue", 
                  "4-cell_set-3_mRNA" = "lightblue", 
                  "2-cell_lin-41_mRNA" = "lightcoral", 
                  "4-cell_lin-41_mRNA" = "lightcoral")

# Create the plot
my_plot <- ggplot(plot_data, aes(x = combined_category, y = abundance, fill = combined_category)) +
  geom_violin(alpha = 0.4, color = "white", size = 0.5, position = position_dodge(width = 0.75)) +
  geom_boxplot(width = 0.1, position = position_dodge(width = 0.75), outlier.shape = NA) +
  geom_jitter(aes(color = rep), height = 0, width = 0.2, size = 1) +
  labs(title = "Abundance of maternally inherited transcripts by cell stage",
       x = "Cell Stage",
       y = "Total mRNA Abundance",
       fill = "mRNA species",
       color = "Replicate") +  # Set the legend title for color
  scale_fill_manual(values = fill_colors,
                    breaks = names(fill_colors),
                    labels = c("set-3", "set-3", "lin-41", "lin-41")) +
  scale_color_manual(values = c("rep1" = "black", "rep2" = "red", "rep3" = "blue"), 
                     breaks = c("rep1", "rep2", "rep3"), 
                     labels = c("Rep 1", "Rep 2", "Rep 3")) +
  scale_x_discrete(labels = c("2-cell_set-3_mRNA" = "2-cell",
                              "4-cell_set-3_mRNA" = "4-cell",
                              "2-cell_lin-41_mRNA" = "2-cell",
                              "4-cell_lin-41_mRNA" = "4-cell")) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        plot.subtitle = element_text(size = 14),
        axis.title = element_text(size = 13, face = "bold"),
        axis.text = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12)) +
  guides(fill = guide_legend(nrow = 2)) +  # Limit the legend to two rows
  facet_wrap(~ mRNA_type, scales = "free_x")  # Facet wrap by mRNA type

# Display the plot
print(my_plot)



```


```{r}
library(ggplot2)
library(dplyr)

# Define the custom order for combined_category
custom_order <- c("2-cell_set-3_mRNA", "4-cell_set-3_mRNA",
                  "2-cell_lin-41_mRNA", "4-cell_lin-41_mRNA")

# Convert combined_category to a factor to ensure correct ordering on the x-axis
plot_data <- combined_data %>%
  mutate(combined_category = factor(combined_category, levels = custom_order))

# Specify color for each combined_category
fill_colors <- c("2-cell_set-3_mRNA" = "lightblue", 
                  "4-cell_set-3_mRNA" = "lightblue", 
                  "2-cell_lin-41_mRNA" = "lightcoral", 
                  "4-cell_lin-41_mRNA" = "lightcoral")

# Create the plot
my_plot <- ggplot(plot_data, aes(x = combined_category, y = abundance, fill = combined_category)) +
  geom_violin(alpha = 0.4, color = "white", size = 0.5, position = position_dodge(width = 0.75)) +
  geom_boxplot(width = 0.1, position = position_dodge(width = 0.75), outlier.shape = NA) +
  geom_jitter(aes(color = rep), height = 0, width = 0.2, size = 1) +
  labs(title = "Abundance of maternally inherited transcripts by cell stage",
       x = "Cell Stage",
       y = "Total mRNA Abundance",
       fill = "mRNA species",
       color = "Replicate") +  # Set the legend title for color
  scale_fill_manual(values = fill_colors,
                    breaks = names(fill_colors),
                    labels = c("set-3", "set-3", "lin-41", "lin-41")) +
  scale_color_manual(values = c("rep1" = "black", "rep2" = "red", "rep3" = "blue"), 
                     breaks = c("rep1", "rep2", "rep3"), 
                     labels = c("Rep 1", "Rep 2", "Rep 3")) +
  scale_x_discrete(labels = c("2-cell_set-3_mRNA" = "2-cell",
                              "4-cell_set-3_mRNA" = "4-cell",
                              "2-cell_lin-41_mRNA" = "2-cell",
                              "4-cell_lin-41_mRNA" = "4-cell")) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        plot.subtitle = element_text(size = 14),
        axis.title = element_text(size = 13, face = "bold"),
        axis.text = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        strip.background = element_rect(fill = "lightgray", color = "black"),
        strip.text = element_text(size = 14, face = "bold")) +  # Customize facet labels
  guides(fill = guide_legend(nrow = 2)) +  # Limit the legend to two rows
  facet_wrap(~ mRNA_type, scales = "free_x")  # Fixed y-axis across facets

# Display the plot
print(my_plot)


# Save the plot as SVG with specified output path
ggsave("/Users/nalytorres/Documents/01_bigfish/ce-bigfish_total-abundance.svg", my_plot, width = 10, height = 6)


```



